package com.kompact.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val md_theme_light_primary = Color(0xFF1C8F62)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA7F2CE)
val md_theme_light_onPrimaryContainer = Color(0xFF002115)
val md_theme_light_secondary = Color(0xFF2F5978)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E6FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C33)
val md_theme_light_tertiary = Color(0xFFB55300)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBC7)
val md_theme_light_onTertiaryContainer = Color(0xFF371200)
val md_theme_light_background = Color(0xFFF4FBF6)
val md_theme_light_onBackground = Color(0xFF101913)
val md_theme_light_surface = Color(0xFFFAFEFA)
val md_theme_light_onSurface = Color(0xFF191D19)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF71796F)
val md_theme_light_outlineVariant = Color(0xFFC1C9BD)
val md_theme_light_inverseSurface = Color(0xFF2E322E)
val md_theme_light_inverseOnSurface = Color(0xFFF0F2ED)
val md_theme_light_inversePrimary = Color(0xFF8CDAB4)
val md_theme_light_surfaceTint = md_theme_light_primary

// Dark scheme
val md_theme_dark_primary = Color(0xFF8CDAB4)
val md_theme_dark_onPrimary = Color(0xFF003823)
val md_theme_dark_primaryContainer = Color(0xFF005235)
val md_theme_dark_onPrimaryContainer = Color(0xFFA7F2CE)
val md_theme_dark_secondary = Color(0xFFA0C9F5)
val md_theme_dark_onSecondary = Color(0xFF003252)
val md_theme_dark_secondaryContainer = Color(0xFF184263)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E6FF)
val md_theme_dark_tertiary = Color(0xFFFFB684)
val md_theme_dark_onTertiary = Color(0xFF522300)
val md_theme_dark_tertiaryContainer = Color(0xFF753500)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBC7)
val md_theme_dark_background = Color(0xFF101315)
val md_theme_dark_onBackground = Color(0xFFE0E3E0)
val md_theme_dark_surface = Color(0xFF181B1C)
val md_theme_dark_onSurface = Color(0xFFC5C8C3)
val md_theme_dark_surfaceVariant = Color(0xFF434948)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BD)
val md_theme_dark_outline = Color(0xFF8A9388)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_inverseSurface = Color(0xFFE0E3DE)
val md_theme_dark_inverseOnSurface = Color(0xFF101410)
val md_theme_dark_inversePrimary = Color(0xFF1C8F62)
val md_theme_dark_surfaceTint = md_theme_dark_primary
